# yaml
name: ci

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.11'
          cache: true

      - name: Go mod tidy check
        run: |
          go mod tidy
          git diff --exit-code

      - name: Build
        run: go build ./...

      - name: Test
        run: |
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out

      - name: Generate Coverage Badge
        uses: tj-actions/coverage-badge-go@v3
        id: coverage
        with:
          filename: coverage.out

      - name: Verify changed files
        id: verify
        uses: tj-actions/verify-changed-files@v20
        with:
          files: README.md

      - name: Commit & Push updated badge and README
        if: steps.verify.outputs.files_changed == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git branch -f ${{ github.head_ref }} HEAD
          git checkout ${{ github.head_ref }}

          if [ ! -f coverage-badge.svg ]; then
            echo "SVG not found, skipping commit"
            exit 0
          fi

          git add README.md coverage-badge.svg
  
          git commit -m "chore: Update coverage badge [ci skip]" || echo "No changes to commit"

          git push origin ${{ github.head_ref }} --force-with-lease

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55.2
          args: --timeout=5m

      - name: Vulnerability check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
